import type {
  InboxEmail,
  Job,
  JobNote,
  NotificationItem,
  Property,
} from "@/lib/types";

export const OPERATOR = {
  name: "Charlie",
  role: "Administrator",
  email: "charlie@abnmaintenance.co.uk",
};

export const properties: Property[] = [
  {
    id: "prop-sycamore",
    name: "60 Sycamore Drive",
    address: "60 Sycamore Drive, Beck Row",
    postcode: "IP28 8AB",
    organisation: "Baselets",
    tenant: "Esteban Coronado",
    type: "House",
    bedrooms: 3,
  },
  {
    id: "prop-king",
    name: "14 King Street",
    address: "14 King Street, Mildenhall",
    postcode: "IP28 7EY",
    organisation: "HomeLet East",
    tenant: "Sarah Mitchell",
    type: "Flat",
    bedrooms: 2,
  },
  {
    id: "prop-church",
    name: "8 Church Lane",
    address: "8 Church Lane, Lakenheath",
    postcode: "IP27 9DS",
    organisation: "Baselets",
    tenant: "James Okonkwo",
    type: "House",
    bedrooms: 3,
  },
  {
    id: "prop-high",
    name: "22 High Street",
    address: "22 High Street, Newmarket",
    postcode: "CB8 8LB",
    organisation: "Flagship Housing",
    tenant: "Priya Sharma",
    type: "Maisonette",
    bedrooms: 2,
  },
  {
    id: "prop-meadows",
    name: "3 The Meadows",
    address: "3 The Meadows, Bury St Edmunds",
    postcode: "IP33 2AF",
    organisation: "Havebury Housing",
    tenant: "Tom Harrington",
    type: "House",
    bedrooms: 4,
  },
  {
    id: "prop-stjohns",
    name: "19 St John's Close",
    address: "19 St John's Close, Brandon",
    postcode: "IP27 0HY",
    organisation: "Baselets",
    tenant: "Aisha Khan",
    type: "Flat",
    bedrooms: 1,
  },
];

export const jobs: Job[] = [
  {
    id: "39206",
    jobNo: "39206",
    tenant: "Esteban Coronado",
    tenantPhone: "07700 900216",
    tenantEmail: "esteban.coronado@email.com",
    address: "60 Sycamore Drive, Beck Row",
    organisation: "Baselets",
    priority: "P1",
    status: "New",
    category: "Heating",
    description:
      "Boiler will not fire and the property has no heating or hot water. Tenant reports the house has been cold overnight. Immediate attendance requested.",
    propertyId: "prop-sycamore",
    createdAt: "2026-08-29T08:14:00.000Z",
    updatedAt: "2026-08-29T08:14:00.000Z",
  },
  {
    id: "39205",
    jobNo: "39205",
    tenant: "Sarah Mitchell",
    tenantPhone: "07700 900441",
    tenantEmail: "s.mitchell@email.com",
    address: "14 King Street, Mildenhall",
    organisation: "HomeLet East",
    priority: "P2",
    status: "In Progress",
    category: "Plumbing",
    description:
      "Kitchen mixer tap leaking from the base. Water pooling on the worktop and dripping into the cupboard below.",
    propertyId: "prop-king",
    createdAt: "2026-08-28T16:40:00.000Z",
    updatedAt: "2026-08-29T09:05:00.000Z",
  },
  {
    id: "39204",
    jobNo: "39204",
    tenant: "James Okonkwo",
    tenantPhone: "07700 900118",
    tenantEmail: "james.okonkwo@email.com",
    address: "8 Church Lane, Lakenheath",
    organisation: "Baselets",
    priority: "P3",
    status: "Allocated",
    category: "General",
    description:
      "Oven door hinge has failed and the door will not stay closed. Tenant unable to use the cooker safely.",
    propertyId: "prop-church",
    createdAt: "2026-08-27T11:22:00.000Z",
    updatedAt: "2026-08-28T08:10:00.000Z",
  },
  {
    id: "39203",
    jobNo: "39203",
    tenant: "Priya Sharma",
    tenantPhone: "07700 900772",
    tenantEmail: "priya.sharma@email.com",
    address: "22 High Street, Newmarket",
    organisation: "Flagship Housing",
    priority: "P2",
    status: "On Hold",
    category: "Damp",
    description:
      "Black mould on the bedroom external wall and around the window reveal. Awaiting ventilation survey before works proceed.",
    propertyId: "prop-high",
    createdAt: "2026-08-26T09:48:00.000Z",
    updatedAt: "2026-08-28T14:33:00.000Z",
  },
  {
    id: "39202",
    jobNo: "39202",
    tenant: "Tom Harrington",
    tenantPhone: "07700 900305",
    tenantEmail: "tom.harrington@email.com",
    address: "3 The Meadows, Bury St Edmunds",
    organisation: "Havebury Housing",
    priority: "P1",
    status: "Completed",
    category: "Heating",
    description:
      "No hot water throughout the property. Engineer replaced a failed diverter valve and confirmed the system is back in service.",
    propertyId: "prop-meadows",
    createdAt: "2026-08-24T07:05:00.000Z",
    updatedAt: "2026-08-24T15:40:00.000Z",
  },
  {
    id: "39201",
    jobNo: "39201",
    tenant: "Aisha Khan",
    tenantPhone: "07700 900864",
    tenantEmail: "aisha.khan@email.com",
    address: "19 St John's Close, Brandon",
    organisation: "Baselets",
    priority: "P4",
    status: "Completed",
    category: "Electrical",
    description:
      "Bathroom extractor fan noisy and slow to start. Fan replaced and circuit tested.",
    propertyId: "prop-stjohns",
    createdAt: "2026-08-22T13:18:00.000Z",
    updatedAt: "2026-08-23T10:02:00.000Z",
  },
];

export const emails: InboxEmail[] = [
  {
    id: "mail-39206",
    fromName: "Baselets Repairs",
    fromEmail: "repairs@baselets.co.uk",
    subject: "P1 — No heating at 60 Sycamore Drive, Beck Row",
    preview:
      "Please raise an emergency job. Tenant Esteban Coronado reports the boiler will not fire...",
    body: "Please raise an emergency job. Tenant Esteban Coronado reports the boiler will not fire and there is no heating or hot water. Access is available all day. Keysafe code on file.",
    receivedAt: "2026-08-29T08:12:00.000Z",
    read: false,
    jobId: "39206",
  },
  {
    id: "mail-39205",
    fromName: "Sarah Mitchell",
    fromEmail: "s.mitchell@email.com",
    subject: "Kitchen tap still dripping — 14 King Street",
    preview:
      "Just checking the plumber is still coming this morning. The cupboard below the sink is wet...",
    body: "Just checking the plumber is still coming this morning. The cupboard below the sink is wet and I have put a bowl under the pipe. Please can someone call when they are 20 minutes away.",
    receivedAt: "2026-08-29T07:41:00.000Z",
    read: false,
    jobId: "39205",
  },
  {
    id: "mail-39203",
    fromName: "Flagship Housing",
    fromEmail: "works@flagship-housing.org",
    subject: "Hold works — damp survey required at 22 High Street",
    preview:
      "Please place job 39203 on hold until the ventilation survey is returned...",
    body: "Please place job 39203 on hold until the ventilation survey is returned. Do not instruct mould wash until we confirm the extract rate in the bedroom.",
    receivedAt: "2026-08-28T14:20:00.000Z",
    read: true,
    jobId: "39203",
  },
  {
    id: "mail-39204",
    fromName: "James Okonkwo",
    fromEmail: "james.okonkwo@email.com",
    subject: "Oven door hanging off",
    preview:
      "The oven door dropped this afternoon and I cannot close it. I have unplugged the cooker...",
    body: "The oven door dropped this afternoon and I cannot close it. I have unplugged the cooker. Happy for an engineer any weekday after 10am.",
    receivedAt: "2026-08-27T11:18:00.000Z",
    read: true,
    jobId: "39204",
  },
  {
    id: "mail-complete",
    fromName: "Havebury Housing",
    fromEmail: "repairs@havebury.com",
    subject: "Completion confirmation — 3 The Meadows",
    preview:
      "Tenant has confirmed hot water is restored. Please close job 39202...",
    body: "Tenant has confirmed hot water is restored. Please close job 39202 and send the invoice to the usual repairs inbox.",
    receivedAt: "2026-08-24T16:05:00.000Z",
    read: true,
    jobId: "39202",
  },
];

export const notes: JobNote[] = [
  {
    id: "note-39205-1",
    jobId: "39205",
    author: "Charlie",
    body: "Plumber booked for this morning. Tenant asked for a call 20 minutes before arrival.",
    createdAt: "2026-08-29T09:06:00.000Z",
  },
  {
    id: "note-39203-1",
    jobId: "39203",
    author: "Charlie",
    body: "On hold at Flagship's request until the ventilation survey is back.",
    createdAt: "2026-08-28T14:34:00.000Z",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "ntf-1",
    title: "New P1 job",
    body: "Job 39206 raised for 60 Sycamore Drive — no heating.",
    createdAt: "2026-08-29T08:14:00.000Z",
    read: false,
    href: "/jobs/39206",
  },
  {
    id: "ntf-2",
    title: "Tenant chasing attendance",
    body: "Sarah Mitchell emailed about the leaking kitchen tap.",
    createdAt: "2026-08-29T07:41:00.000Z",
    read: false,
    href: "/emails",
  },
];
